### ISSUE TITLE
Question: Session History

### ISSUE THREAD

**Issue by chaseconey** [racehub-io/f1-telemetry-client#62]
Hey there 👋 .

First, I just want to say that I love the client that you have produced here, it has been great to work with to power our league telemetry!

I was curious if there is a road map for getting some of the newer 2021 features added to the client, specifically the Session History. It seems that with some of the removals from 2020, the only way to get some of the data that we look for is to parse it out of the history when we need it, so we are a bit stuck on the 2020 packet spec for now.

Also, a small request for us dependent folks - it would be fantastic if breaking changes, like moving to the new UDP specification was a breaking change (increment the largest number). That way downstream dependents don't accidentally get the new 2021 client.

Thanks!

**Comment by schmedia-dev** [comment]
I need it too so I will try to do this and create a pull request.

Haven't done a contribution before, so it could take some time 😆

**Comment by jonybur** [comment]
Hey all. Thanks for the comments & contributions. I've been a bit busy lately so adding the new parsers is taking me some time but I'll get on it if you guys require it. @schmedia-dev  already gave me a head start so that's fantastic. Also agree with the comment on versioning. Will have that in mind for the next update.

AFAIK there's some bugs related to 2021 specs (specifically around lap times) so be wary when using 2021 versions. However, this is independent from the fact that we need the new packages to be included soon. Will do that this weekend.

Thanks again
